### ISSUE TITLE
Kore 2.2.0 plays back different songs than the ones selected

### ISSUE THREAD

**Issue by mvglasow** [xbmc/Kore#362]
Steps to reproduce:

1. Launch Kore and connect to your media center
2. Tap the hamburger menu and select Music
3. Search for a track you’d like to hear, tap its menu button and select “Play”.

Expected result:

I would expect OSMC to play the song I selected.

Actual result:

On Kore 2.1.0, actual result = expected result. On Kore 2.2.0, the playlist will be filled with one or more random songs. I retried multiple times, selecting the same song each time, and got different playlists each time.

After removing Kore 2.2.0, installing 2.1.0 and setting up the media center from scratch, everything was back to normal. Upgrading to 2.2.0 again brought the bug back—seems it’s really the Kore version.

Software used:

Kore 2.2.0, downloaded from F-Droid.
Android 7.1 (LineageOS 14.1-20170123-NIGHTLY-bacon) on OnePlus One
OSMC 17.1 on Raspberry Pi 3. (Originally I had an earlier version, which had the same error with Kore 2.2.0, then upgraded and the error remained.)

**Comment by poisdeux** [comment]
Thanks for catching this. My bad, I have no idea why, but I removed setting the songId for the playlist item to play, queue, or download in commit 49a253af340e1f1aba0d671aa47f531c77ec7823
PR #363 should fix this.

**Comment by SyncedSynapse** [comment]
In a few days there should be a new version on the mirrors with the fix applied.
http://mirrors.kodi.tv/tools/kore/nightlies/

I'm going to close this now, as i'm pretty sure that it is fixed, but if for any reason you still get the issue, please reopen it. Thanks.

**Comment by poisdeux** [comment]
Reopening to hopefully reduce the number of people creating similar issues.
I'll close this when the new version is released.

**Comment by georgek** [comment]
Is this actually fixed? I've downloaded version 2.2.0 from both the Play store and F-droid and both have this problem. Am I supposed to find a newer version somewhere else?

**Comment by MartijnKaijser** [comment]
http://mirrors.kodi.tv/tools/kore/nightlies/

**Comment by poisdeux** [comment]
Closing this as new version 2.3.0 should contain a fix for this. Please reopen if it was not fixed.

**Comment by Benance** [comment]
Hello, despite it was considered as a "bug", this behaviour was (for me) a very interesting fonctionnality:
I was a fast way to play randomly all my music library.
Now, the bug is fixed and I havn't found any solution to randomly play my music library again with Kore.
Il there a way to do this?
Thanks a lot for your answers.
Regards.

**Comment by poisdeux** [comment]
Please create a new issue and add feature request in the title or add the label enhancement

**Comment by georgek** [comment]
https://xkcd.com/1172/

**Comment by ABuijert** [comment]
For me the version in the android Playstore (2.5.3) still has this issue. The version on f-droid (2.5.1) works fine. For me it shows when selecting a music artist or music album.
